spring.application.name=entrace

server.port = 8080

#GateWay
#spring.cloud.gateway.server.webflux.routes[0].id=user-service
#spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.server.webmvc.routes[0].id=service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**


#AuthenticationServer(Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8083/realms/Verifier


#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379